In [1]:
import warnings
warnings.simplefilter("ignore")

import pickle
import pandas as pd
import numpy as np

import os

from recbole.config import Config
from recbole.evaluator.evaluator import Evaluator
    
import torch

In [ ]:
#take struct from a dataset
dataset = "Amazon_Luxury_Beauty" 
model_name = "Pop"
list_file = os.listdir("../struct/")
file_for_dataset = [x for x in list_file if dataset in x]
assert len(file_for_dataset) == 1


def get_measure(num_item:int, curr_rec, k, metrics=["IID_AID"]):
    with open("../struct/"+file_for_dataset[0],"rb") as f:
        struct = pickle.load(f)
    config = Config(
                    model=model_name, 
                    dataset=dataset, 
                    config_file_list=["../RecBole/recbole/properties/overall.yaml"],
                    config_dict={
                        "topk":k,
                        "metrics":metrics}
                                )
    evaluator = Evaluator(config)
    struct.set("data.num_items", num_item+1) #because -1 in metrics.py
    struct.set("rec.items", curr_rec)

    return evaluator.evaluate(struct)

# Gini-w

In [ ]:
import itertools
permute_item = list(itertools.permutations([1, 2,3]))
rel = [1,1,1,1,1,1]
k = 3
num_item = 3


for Ru1 in permute_item:
    for Ru2 in permute_item:
        curr_rec = np.array([Ru1,Ru2])
        curr_rec = torch.Tensor(curr_rec).int()

        num_pos_item = torch.Tensor(curr_rel).sum(axis=1)
        num_pos_item = num_pos_item[:,np.newaxis]

        result = get_measure(num_item, curr_rec, k, metrics=["FairWORel"])

        print(curr_rec, result[f"Gini-w_ori@{k}"])


nan
tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32) 0.156426242
nan
tensor([[1, 2, 3],
        [1, 3, 2]], dtype=torch.int32) 0.1359453927
nan
tensor([[1, 2, 3],
        [2, 1, 3]], dtype=torch.int32) 0.0986939703
nan
tensor([[1, 2, 3],
        [2, 3, 1]], dtype=torch.int32) 0.078213121
nan
tensor([[1, 2, 3],
        [3, 1, 2]], dtype=torch.int32) 0.078213121
nan
tensor([[1, 2, 3],
        [3, 2, 1]], dtype=torch.int32) 0.0372514224
nan
tensor([[1, 3, 2],
        [1, 2, 3]], dtype=torch.int32) 0.1359453927
nan
tensor([[1, 3, 2],
        [1, 3, 2]], dtype=torch.int32) 0.156426242
nan
tensor([[1, 3, 2],
        [2, 1, 3]], dtype=torch.int32) 0.078213121
nan
tensor([[1, 3, 2],
        [2, 3, 1]], dtype=torch.int32) 0.0372514224
nan
tensor([[1, 3, 2],
        [3, 1, 2]], dtype=torch.int32) 0.0986939703
nan
tensor([[1, 3, 2],
        [3, 2, 1]], dtype=torch.int32) 0.078213121
nan
tensor([[2, 1, 3],
        [1, 2, 3]], dtype=torch.int32) 0.0986939703
nan
tensor([[2, 1, 3],
        

# II-D & AI-D

Check II-D and AI-D

In [ ]:
import itertools
permute_item = list(itertools.permutations([1, 2, 3]))
k = 1
num_item = 3


for Ru1 in permute_item:
    for Ru2 in permute_item:
        curr_rec = np.array([Ru1,Ru2])
        curr_rec = torch.Tensor(curr_rec).int()
        result = get_measure(num_item, curr_rec, k)

        print(curr_rec, result)


tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.2222222222)])
tensor([[1, 2, 3],
        [1, 3, 2]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.2222222222)])
tensor([[1, 2, 3],
        [2, 1, 3]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.0555555556)])
tensor([[1, 2, 3],
        [2, 3, 1]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.0555555556)])
tensor([[1, 2, 3],
        [3, 1, 2]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.0555555556)])
tensor([[1, 2, 3],
        [3, 2, 1]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.0555555556)])
tensor([[1, 3, 2],
        [1, 2, 3]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.2222222222), ('AI-D_ori@1', 0.2222222222)])
tensor([[1, 3, 2],
        [1, 3, 2]], dtype=torch.int32) OrderedDict([('II-

In [ ]:
round(2/9,10)

0.2222222222

In [ ]:
round(1/18,10)

0.0555555556

In [ ]:
import itertools
permute_item = list(itertools.permutations([1, 2]))
k = 1
num_item = 2


for Ru1 in permute_item:
    for Ru2 in permute_item:
        curr_rec = np.array([Ru1,Ru2])
        curr_rec = torch.Tensor(curr_rec).int()
        result = get_measure(num_item, curr_rec, k)

        print(curr_rec, result)


tensor([[1, 2],
        [1, 2]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.25), ('AI-D_ori@1', 0.25)])
tensor([[1, 2],
        [2, 1]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.25), ('AI-D_ori@1', 0.0)])
tensor([[2, 1],
        [1, 2]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.25), ('AI-D_ori@1', 0.0)])
tensor([[2, 1],
        [2, 1]], dtype=torch.int32) OrderedDict([('II-D_ori@1', 0.25), ('AI-D_ori@1', 0.25)])


In [2]:
import numpy as np

# Simulate AI-D and II-D for multiple rounds

In [1]:
import numpy as np
import itertools
import pandas as pd

In [3]:
def calc_Eui_tilde(num_item, k, gamma=0.8):
    return 1/num_item * (1-gamma**k)/(1-gamma)

def calc_IID_AID(num_item, E_ui, Eui_tilde, k):
    Eui_tilde_mat = np.full(shape=E_ui.shape,fill_value=Eui_tilde)
    diff = E_ui - Eui_tilde_mat
    II_D = np.power(diff, 2).mean()
    AI_D = np.power(diff.mean(0),2).mean()
    return {"II_D":II_D, "AI_D": AI_D}

def simulate_IID_AID_multi_round(k, num_item, num_round):

    permute_item = list(itertools.permutations([i+1 for i in range(num_item)]))

    Eui_tilde = calc_Eui_tilde(num_item,k)
    Eui_combin = []

    list_rec = []

    for Ru1 in permute_item:
        for Ru2 in permute_item:
            rec = np.array([Ru1,Ru2])[:,:k] #only top k
            if str(rec) not in list_rec:
                list_rec.append(str(rec))
            else:
                continue
            
            m = rec.shape[0]

            gamma = 0.8

            #build user-item matrix
            rank_matrix = np.zeros((m, num_item))
            for i in range(len(rec)):
                rank_matrix[i][rec[i]-1] = np.where(rec[i])[0]+1
            
            user_item_exp_rbp = np.copy(rank_matrix)

            user_item_exp_rbp[user_item_exp_rbp.nonzero()] = gamma**(user_item_exp_rbp[user_item_exp_rbp.nonzero()]-1)

            Eui_combin.append(user_item_exp_rbp)

    combin_across_two_rounds = itertools.combinations_with_replacement(Eui_combin,num_round)

    list_of_measures = []
    list_Eui = []

    for combin in combin_across_two_rounds:
        E_ui = sum(combin)/len(combin)
        if str(E_ui) in list_Eui:
            continue

        IID_AID = calc_IID_AID(num_item, E_ui, Eui_tilde, k)
        list_Eui.append(str(E_ui))
        list_of_measures.append(IID_AID)

    return list_Eui, list_of_measures

## Cause 2 (not enough slots)

In [4]:
k = 1
num_item = 5
num_round = 2

list_Eui, list_of_measures = simulate_IID_AID_multi_round(k, num_item, num_round)
    

In [5]:
list_of_measures

[{'II_D': 0.16000000000000006, 'AI_D': 0.16000000000000006},
 {'II_D': 0.11000000000000003, 'AI_D': 0.08500000000000003},
 {'II_D': 0.11000000000000003, 'AI_D': 0.085},
 {'II_D': 0.11000000000000003, 'AI_D': 0.085},
 {'II_D': 0.11000000000000003, 'AI_D': 0.08500000000000002},
 {'II_D': 0.11000000000000003, 'AI_D': 0.08500000000000003},
 {'II_D': 0.06000000000000001, 'AI_D': 0.06000000000000001},
 {'II_D': 0.06000000000000001, 'AI_D': 0.035},
 {'II_D': 0.06000000000000001, 'AI_D': 0.035},
 {'II_D': 0.06, 'AI_D': 0.035},
 {'II_D': 0.11000000000000003, 'AI_D': 0.085},
 {'II_D': 0.06000000000000001, 'AI_D': 0.035},
 {'II_D': 0.06000000000000001, 'AI_D': 0.06000000000000001},
 {'II_D': 0.06000000000000001, 'AI_D': 0.035},
 {'II_D': 0.06, 'AI_D': 0.035},
 {'II_D': 0.11000000000000003, 'AI_D': 0.085},
 {'II_D': 0.06000000000000001, 'AI_D': 0.035},
 {'II_D': 0.06000000000000001, 'AI_D': 0.035},
 {'II_D': 0.06000000000000001, 'AI_D': 0.06000000000000001},
 {'II_D': 0.06, 'AI_D': 0.035},
 {'II_D

In [6]:
list_Eui

['[[1. 0. 0. 0. 0.]\n [1. 0. 0. 0. 0.]]',
 '[[1.  0.  0.  0.  0. ]\n [0.5 0.5 0.  0.  0. ]]',
 '[[1.  0.  0.  0.  0. ]\n [0.5 0.  0.5 0.  0. ]]',
 '[[1.  0.  0.  0.  0. ]\n [0.5 0.  0.  0.5 0. ]]',
 '[[1.  0.  0.  0.  0. ]\n [0.5 0.  0.  0.  0.5]]',
 '[[0.5 0.5 0.  0.  0. ]\n [1.  0.  0.  0.  0. ]]',
 '[[0.5 0.5 0.  0.  0. ]\n [0.5 0.5 0.  0.  0. ]]',
 '[[0.5 0.5 0.  0.  0. ]\n [0.5 0.  0.5 0.  0. ]]',
 '[[0.5 0.5 0.  0.  0. ]\n [0.5 0.  0.  0.5 0. ]]',
 '[[0.5 0.5 0.  0.  0. ]\n [0.5 0.  0.  0.  0.5]]',
 '[[0.5 0.  0.5 0.  0. ]\n [1.  0.  0.  0.  0. ]]',
 '[[0.5 0.  0.5 0.  0. ]\n [0.5 0.5 0.  0.  0. ]]',
 '[[0.5 0.  0.5 0.  0. ]\n [0.5 0.  0.5 0.  0. ]]',
 '[[0.5 0.  0.5 0.  0. ]\n [0.5 0.  0.  0.5 0. ]]',
 '[[0.5 0.  0.5 0.  0. ]\n [0.5 0.  0.  0.  0.5]]',
 '[[0.5 0.  0.  0.5 0. ]\n [1.  0.  0.  0.  0. ]]',
 '[[0.5 0.  0.  0.5 0. ]\n [0.5 0.5 0.  0.  0. ]]',
 '[[0.5 0.  0.  0.5 0. ]\n [0.5 0.  0.5 0.  0. ]]',
 '[[0.5 0.  0.  0.5 0. ]\n [0.5 0.  0.  0.5 0. ]]',
 '[[0.5 0.  0.  0.5 0.

In [7]:
import pandas as pd
df_cause2 = pd.DataFrame(list_of_measures)
df_cause2


II_D   AI_D
0    0.16  0.160
1    0.11  0.085
2    0.11  0.085
3    0.11  0.085
4    0.11  0.085
..    ...    ...
220  0.11  0.035
221  0.11  0.085
222  0.16  0.060
223  0.11  0.085
224  0.16  0.160

[225 rows x 2 columns]

In [8]:
df_cause2.min()


II_D    0.06
AI_D    0.01
dtype: float64

In [9]:
df_cause2.idxmin()


II_D     9
AI_D    35
dtype: int64

In [10]:
list_Eui[35]

'[[0.5 0.  0.5 0.  0. ]\n [0.  0.5 0.  0.5 0. ]]'

In [11]:
df_cause2.max()

II_D    0.16
AI_D    0.16
dtype: float64

## Cause 3 (number of slots is not divisible by number of items)

In [18]:
k = 2
num_item = 3
num_round = 2

list_Eui, list_of_measures = simulate_IID_AID_multi_round(k, num_item, num_round)

In [19]:
list_Eui

['[[1.  0.8 0. ]\n [1.  0.8 0. ]]',
 '[[1.  0.8 0. ]\n [1.  0.4 0.4]]',
 '[[1.  0.8 0. ]\n [0.9 0.9 0. ]]',
 '[[1.  0.8 0. ]\n [0.5 0.9 0.4]]',
 '[[1.  0.8 0. ]\n [0.9 0.4 0.5]]',
 '[[1.  0.8 0. ]\n [0.5 0.8 0.5]]',
 '[[1.  0.4 0.4]\n [1.  0.8 0. ]]',
 '[[1.  0.4 0.4]\n [1.  0.4 0.4]]',
 '[[1.  0.4 0.4]\n [0.9 0.9 0. ]]',
 '[[1.  0.4 0.4]\n [0.5 0.9 0.4]]',
 '[[1.  0.4 0.4]\n [0.9 0.4 0.5]]',
 '[[1.  0.4 0.4]\n [0.5 0.8 0.5]]',
 '[[0.9 0.9 0. ]\n [1.  0.8 0. ]]',
 '[[0.9 0.9 0. ]\n [1.  0.4 0.4]]',
 '[[0.9 0.9 0. ]\n [0.9 0.9 0. ]]',
 '[[0.9 0.9 0. ]\n [0.5 0.9 0.4]]',
 '[[0.9 0.9 0. ]\n [0.9 0.4 0.5]]',
 '[[0.9 0.9 0. ]\n [0.5 0.8 0.5]]',
 '[[0.5 0.9 0.4]\n [1.  0.8 0. ]]',
 '[[0.5 0.9 0.4]\n [1.  0.4 0.4]]',
 '[[0.5 0.9 0.4]\n [0.9 0.9 0. ]]',
 '[[0.5 0.9 0.4]\n [0.5 0.9 0.4]]',
 '[[0.5 0.9 0.4]\n [0.9 0.4 0.5]]',
 '[[0.5 0.9 0.4]\n [0.5 0.8 0.5]]',
 '[[0.9 0.4 0.5]\n [1.  0.8 0. ]]',
 '[[0.9 0.4 0.5]\n [1.  0.4 0.4]]',
 '[[0.9 0.4 0.5]\n [0.9 0.9 0. ]]',
 '[[0.9 0.4 0.5]\n [0.5 0.9 

In [20]:
df_cause3 = pd.DataFrame(list_of_measures)
df_cause3

II_D      AI_D
0    0.186667  0.186667
1    0.133333  0.106667
2    0.183333  0.181667
3    0.116667  0.081667
4    0.116667  0.081667
..        ...       ...
436  0.116667  0.095000
437  0.183333  0.181667
438  0.186667  0.080000
439  0.133333  0.106667
440  0.186667  0.186667

[441 rows x 2 columns]

In [21]:
df_cause3.min()

II_D    0.020
AI_D    0.005
dtype: float64

In [22]:
df_cause3.max()

II_D    0.186667
AI_D    0.186667
dtype: float64

## Manual check for II-D/AI-D cause 3

In [5]:
# sum(np.array([0.4, 0.4, 0.2, 0.2, -0.6, -0.6])**2)/2/3

0.18666666666666668